// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	geom "github.com/twpayne/go-geom"
)

type Person struct {
	ID       int32
	Name     string
	Age      int32
	Location geom.T
}
